language: java
before_install:
  - wget  http://download.opensuse.org/repositories/openSUSE:Tools/xUbuntu_13.10/Release.key
  - sudo apt-key add Release.key 
  - sudo apt-add-repository "deb http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_13.10/ /"
  - sudo apt-get update -qq
  - sudo apt-get install libwebkitgtk-1.0-0 osc
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: mvn integration-test -B

