language: java
before_install:
- sudo apt-get install libwebkitgtk-1.0-0 devscripts maven
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bin/upload
env:
  global:
  - secure: bQ9qCG/0Q0Cmkm5RAofvxj3yz8t0Lhg9CmP1jKN/BoCSsGrJwt7iqNZaSqGpgoRGfVxyfiNc4dZSU+vvr5iXuwewEWaI347gGiCJvjQA2I/rGGfohqIFfMAsyBOaNlntO+hS6Q3zuIHa2gA/cminDRzDghLm/Q/aUB2Dz7s7BHk=
  - secure: TTakkqHgYO4W9oO3phGGHyxNqdgZRgNXlnWQQ61IBOhMJsIyYclTKE4ZKPdRiEIhQRFYWi0RNq2So9CJUqq1X8bJVEjcL1GbGccdvb0kz325ZZuBDOLqzzFVXGe1tCLUvaedKFvW4IfuKhrP0mqXi1WUncluHJGVDPmHVYoa52I=
